server:
  port: 5432

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SixsectorHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: liudaolunhui
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.105.71.128:7832/thesixsectorteam?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        # 数据源-2，名称为 test
#        test:
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/sixrealms?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: city.thesixsectorteam.wheelworld.system.domain,city.thesixsectorteam.wheelworld.job.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


sixsector:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**,/favicon.ico
    # token有效期，单位秒
    jwtTimeOut: 3600
  # Swagger相关配置1
  swagger:
    basePackage: city.thesixsectorteam.wheelworld
    title: 六道轮回世界接口文档
    description: Six Realms Wheel World API Document.
    version: 2.0
    author: sixrealms
    url: https://thesixsectorteam.city
    email: xxxx@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
